nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/display-name: Rancher Developer Portal
    catalog.cattle.io/rancher-version: ">= 2.7.0-0 < 2.9.0-0"
